[tool.poetry]
name = "flightgear_python"
version = "1.0.0"
description = "Interface for FlightGear network connections"
authors = ["Julianne Swinoga <julianneswinoga@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
construct = ">=2.10"

[tool.poetry.dev-dependencies]
sphinx = ">=5.1.1"
sphinx-rtd-theme = ">=1.0.0"

[tool.poetry.urls]
"homepage" = "https://github.com/julianneswinoga/flightgear-python"
"repository" = "https://github.com/julianneswinoga/flightgear-python"
"documentation" = "https://flightgear-python.readthedocs.io/en/latest"
"Bug Tracker" = "https://github.com/julianneswinoga/flightgear-python/issues"
