[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "flightgear_python"
authors = [{name = "Julianne Swinoga", email = "julianneswinoga@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">=3.6"
dependencies = [
    "construct>=2.10",
]

[project.optional-dependencies]
test = [
]
doc = [
    "sphinx>=5.1.1",
    "sphinx-rtd-theme>=1.0.0",
]

[project.urls]
Home = "https://github.com/julianneswinoga/flightgear-python"
Documentation = "https://flightgear-python.readthedocs.io/en/latest"
Bug-Tracker = "https://github.com/julianneswinoga/flightgear-python/issues"
