version: 2.1

orbs:
  python: circleci/python@2.0.3

executor-defaults: &executor-defaults
  executor:
    name: python/default
    tag: "3.6"

jobs:
  build_install_test:
    <<: *executor-defaults
    steps:
      - checkout
      - run:
          name: Poetry build
          command: poetry build --no-ansi --no-interaction
      - run:
          name: Poetry install
          command: poetry install --no-ansi --no-interaction
      - run:
          name: Install coverage
          command: pip install -U coverage coveralls
      - run:
          name: Run pytest
          command: poetry run coverage run -m pytest tests/
      - run:
          name: Coveralls
          command: coveralls
      - persist_to_workspace:
          root: .
          paths:
            - dist
  poetry_publish:
    <<: *executor-defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Poetry config
          command: poetry config --no-ansi --no-interaction repositories.testpypi https://test.pypi.org/legacy/
      - run:
          name: Poetry publish
          command: poetry publish -vv --no-ansi --no-interaction --username __token__ --password ${FLIGHTGEAR_PYPI_TOKEN} --repository testpypi

workflows:
  main-workflow:
    jobs:
      - build_install_test:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - poetry_publish:
          requires:
            - build_install_test
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
