version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: "3.6"
    steps:
      - checkout
      - run:
          name: Poetry build
          command: poetry build --no-ansi
      - run:
          name: Poetry install
          command: poetry install --no-ansi
      - run:
          name: Install coverage
          command: pip install -U coverage coveralls
      - run:
          name: Run pytest
          command: poetry run coverage run -m pytest tests/
      - run:
          name: Coveralls
          command: coveralls

workflows:
  main:
    jobs:
      - build-and-test
